# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install packages
        run: sudo apt install -y libasound2-dev

      - name: Test
        run: go test -v ./...

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Build
        run: gox -output="./output/radio_{{.OS}}_{{.Arch}}" -osarch="windows/amd64 windows/386 linux/amd64 darwin/amd64"
#       run: gox -output="./output/radio_{{.OS}}_{{.Arch}}" -osarch="windows/amd64 windows/386 linux/amd64"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: GoRadio binaries
          # A file, directory or wildcard pattern that describes what to upload
          path: ./output/*
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          retention-days: 7
